apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-ms
  labels:
    app: comment-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-ms
  template:
    metadata:
      labels:
        app: comment-ms
    spec:
      containers:
        - name: comment-ms
          image: islamahmad/eaproj-commentms:1.0.8
          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-commentms:1.0.8"

            - name: SERVER_PORT
              value: "8080"

            #MONGODB
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: comment-ms
                  key: MONGODB_PASS

          envFrom:
            - configMapRef:
                name: comment-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global
